import { UserSessionProvider } from "@/components/providers/SessionProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <UserSessionProvider>{children}</UserSessionProvider>
      </body>
    </html>
  );
}
